# concat-fuse
# Copyright (C) 2015 Ingo Ruhnke <grumbel@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Build file for https://travis-ci.org/
#
# Configuration manual:
# http://docs.travis-ci.com/user/build-configuration/
#
# Based on:
# https://github.com/supertuxkart/stk-code/blob/master/.travis.yml
# https://github.com/SuperTux/supertux/blob/master/.travis.yml

language: cpp

compiler:
  - gcc
  - clang

matrix:
  fast_finish: true

env:
  global:
    - CMAKE_VERSION=3.2.1 SDL2_VERSION=2.0.3 SDL2IMAGE_VERSION=2.0.0 SDL2MIXER_VERSION=2.0.0
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "AtR7gmKt+2SbicF0q9DycyB0bqDdao1vUp2xOOCqRt5+DNX1bu2+6HudWOduSppduzlc8NhN+Gmewe9Amv80YFM/MgwR+fi+zC5NvxcAyRfKmDYUJGjvMNAJ/YQDg4jyKOiXOiM3NvPTHYh5qAb81fofQXsvGLh3fNTA3x7dduQ="
  matrix:
    - BUILD_TYPE="Debug"
    - BUILD_TYPE="Release"

before_install:
  # gcc repository
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y

  # clang repository
  - sudo add-apt-repository -y "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main"
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -

  - sudo apt-get update -qq
  - >
    sudo apt-get install \
      build-essential \
      cmake \
      libfuse-dev \
      libmhash-dev \
      g++-4.9 \
      clang-3.8

  # patch for mhash, see https://bugs.launchpad.net/ubuntu/+source/mhash/+bug/1465562
  - sudo sed -i "s/_Bool/bool/" /usr/include/mutils/mutils.h

  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.8"; fi

  # CMake
  - wget http://www.cmake.org/files/v3.2/cmake-$CMAKE_VERSION.tar.gz -O - | tar xz
  - (cd cmake-$CMAKE_VERSION && cmake . && make -j3 && sudo make install)

  # minizip
  - wget http://pingus.seul.org/~grumbel/tmp/minizip-1.1.tar.gz -O - | tar xz
  - (cd minizip-1.1 && ./configure --prefix=/usr && make && sudo make install)

script:
  # Clean from previous Travis build
  - git clean -f
  # Then build:
  - mkdir "build-$BUILD_TYPE"
  - cd "build-$BUILD_TYPE"
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWERROR=ON -DWARNINGS=ON -DBUILD_TESTS=ON
  - make VERBOSE=1 -k
  - cd ..
  - build-${BUILD_TYPE}/test_concat_fuse

addons:
  coverity_scan:
    project:
      name: "concat-fuse/concat-fuse"
      description: "Build submitted via Travis CI"
    notification_email: grumbel@gmail.com
    build_command_prepend: "cmake . && make clean"
    build_command: "make"
    branch_pattern: coverity_scan

# EOF #
